# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'stackz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Koloda'	
  # Pods for stackz
	pod 'Firebase/Analytics'
	pod 'Firebase/Storage'
	pod 'Firebase/Database'
  target 'stackzTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'stackzUITests' do
    # Pods for testing
  end

end
